### ISSUE TITLE
Encounter  http.client.NO_CONTENT error

### ISSUE THREAD

**Issue by jiabailie** [richtier/alexa-voice-service-client#4]
Hello,

I want to use this library to generate some answer waves of a question set.
But I encounter http.client.NO_CONTENT.
I have successful generated the refresh token and register a product.
Could you give me some help on this issue? Thanks.

    Traceback (most recent call last):
      File "test.py", line 8, in <module>
        alexa_client.connect()  # authenticate and other handshaking steps
      File "/home/mstts/Documents/Amazon/alexa-voice-service-client/avs_client/avs_client/client.py", line 43, in connect
        self.synchronise_device_state()
      File "/home/mstts/Documents/Amazon/alexa-voice-service-client/avs_client/avs_client/client.py", line 55, in synchronise_device_state
        device_state=self.device_manager.get_device_state(),
      File "/home/mstts/Documents/Amazon/alexa-voice-service-client/avs_client/avs_client/connection.py", line 72, in synchronise_device_state
        assert response.status == http.client.NO_CONTENT
    AssertionError

**Comment by richtier** [comment]
Fixed published. Grab the fix by installing the library from pypi: `pip install avs_client==0.5.2`

**Comment by Prskriti** [comment]
I am also facing somewhat same issue and is not to fix by installing avs_client package also.
Can u anyone help me with this?

**Comment by alokpandey** [comment]
I was trying the sample and got the same error. Can somebody help?
