### ISSUE TITLE
Alexa Voice Service returning new response to Sync Device State

### ISSUE THREAD

**Issue by dirkjot** [richtier/alexa-voice-service-client#44]
When running the streaming_microphone demo (or the Alexa Browser client), the sync device state will error out with a failed assertion.  Debug inspection showed it is returning an OK response. 

```
→ python3  -m alexa_client.demo.streaming_microphone  --client-id="amzn1.application-**" --client-secret="**" --refresh-token='**'
listening. Press CTRL + C to exit.
Say something to Alexa.
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/alexa-voice-service-client/alexa_client/demo/streaming_microphone.py", line 84, in <module>
    refresh_token=parsed.refresh_token,
  File "/alexa-voice-service-client/alexa_client/demo/streaming_microphone.py", line 42, in main
    alexa_client.connect()
  File "/alexa-voice-service-client/alexa_client/alexa_client/client.py", line 35, in connect
    self.synchronise_device_state()
  File "/alexa-voice-service-client/alexa_client/alexa_client/client.py", line 51, in synchronise_device_state
    device_state=self.device_manager.get_device_state(),
  File "/alexa-voice-service-client/alexa_client/alexa_client/connection.py", line 77, in synchronise_device_state
    assert response.status in ( http.client.NO_CONTENT, )
AssertionError
```

**Comment by richtier** [comment]
This has been fixed in the latest version. Please upgrade to 1.5.0  https://pypi.org/project/alexa-client/

Feel free to re-open if this does not solve.

**Comment by richtier** [comment]
Thanks. This is now fixed. Please upgrade to version `1.5.1`.
